- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check if expense user exist or not.
    ansible.builtin.command: id expense
    register: USER # user is a variable that get output from above command.
    ignore_errors: true

  - name: print the user info.
    ansible.builtin.debug:
      msg: "the user is: {{ USER }}"

  - name: creating user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
